# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yd7EtAaMqlKlZUSJ9gXZ1DXZk7AfIeMF
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

conexao = sqlite3.connect('dados_vendas.db')

cursor = conexao.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS vendas1 (
id_venda INTEGER PRIMARY KEY AUTOINCREMENT,
data_venda DATE,
produto TEXT,
categoria TEXT,
valor_venda REAL
)
''')

cursor.execute('''
INSERT INTO vendas1 (data_venda, produto, categoria, valor_venda) VALUES
('2023-01-01', 'Produto A', 'Eletrônicos', 1500.00),
('2023-01-05', 'Produto B', 'Roupas', 350.00),
('2023-02-10', 'Produto C', 'Eletrônicos', 1200.00),
('2023-03-15', 'Produto D', 'Livros', 200.00),
('2023-03-20', 'Produto E', 'Eletrônicos', 800.00),
('2023-04-02', 'Produto F', 'Roupas', 400.00),
('2023-05-05', 'Produto G', 'Livros', 150.00),
('2023-06-10', 'Produto H', 'Eletrônicos', 1000.00),
('2023-07-20', 'Produto I', 'Roupas', 600.00),
('2023-08-25', 'Produto J', 'Eletrônicos', 700.00),
('2023-09-30', 'Produto K', 'Livros', 300.00),
('2023-10-05', 'Produto L', 'Roupas', 450.00),
('2023-11-15', 'Produto M', 'Eletrônicos', 900.00),
('2023-12-20', 'Produto N', 'Livros', 250.00);
''')

conexao.commit()

nome_da_tabela = 'vendas1'

df_vendas = pd.read_sql_query(f"SELECT * FROM {nome_da_tabela}", conexao)

conexao.close()

sns.set_style('darkgrid')

plt.figure(figsize=(10, 6))
sns.countplot(x='categoria', data=df_vendas, hue='categoria', palette='viridis',
              order=df_vendas['categoria'].value_counts().index, legend=False)

plt.title('Contagem de Vendas por Categoria', fontsize=16, fontweight='bold')
plt.xlabel('Categoria', fontsize=12)
plt.ylabel('Número de Vendas', fontsize=12)
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

sns.barplot(x='categoria', y='valor_venda', data=df_vendas, estimator='sum', hue='categoria', palette='viridis',
            order=df_vendas.groupby('categoria')['valor_venda'].sum().sort_values(ascending=False).index, legend=False)

plt.title('Valor Total de Vendas por Categoria', fontsize=16, fontweight='bold')
plt.xlabel('Categoria', fontsize=12)
plt.ylabel('Valor Total de Vendas (R$)', fontsize=12)
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()